services:
  axis-db:
    image: postgres:latest
    container_name: axis-db
    environment:
      POSTGRES_USER: axis_user
      POSTGRES_PASSWORD: axis_password
      POSTGRES_DB: axis_db
    ports:
      - "5434:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  axis-service:
    build:
      context: .
    container_name: axis-service
    ports:
      - "3002:3002"
    depends_on:
      - axis-db
    environment:
      DATABASE_URL: postgresql://axis_user:axis_password@axis-db:5432/axis_db

volumes:
  axis_postgres_data:
