services:
  sbi:
    extends:
      file: ./src/sbi/docker-compose.yml
      service: sbi-service

  sbi-db:
    extends:
      file: ./src/sbi/docker-compose.yml
      service: sbi-db

  axis:
    extends:
      file: ./src/axis/docker-compose.yml
      service: axis-service

  axis-db:
    extends:
      file: ./src/axis/docker-compose.yml
      service: axis-db

  npci:
    extends:
      file: ./src/npci/docker-compose.yml
      service: npci-service

  npci-db:
    extends:
      file: ./src/npci/docker-compose.yml
      service: npci-db

networks:
  upi-network:
    driver: bridge
